# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
    push:
     branches:
        - 'releases/**' #temporary

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # test PR
      - name: Pull Request another repository for update dependency
        uses: ./.github/actions/update-dep-version
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          package_name: unicons
          destination_repo: akandeBolaji/test-pr
          destination_base_branch: master
          user_email: akandebolajidanielofficial@gmail.com
          user_name: akandeBolaji
          pull_request_reviewers: akandeBolaji
